- hosts: localhost
  name: Ensure a specific HNAS CIFS share is not present on the server
  gather_facts: false
  vars:
    login: &login
      api_url: https://172.27.5.11:8444/v7
      api_key: BgB2qWZVkE.e53OLShtF3If9UIVdTNmvW9dS7ObPqYNPM83OQoeAj9
      validate_certs: false
  tasks:
    - hv_hnas_share_export:
        state: absent
        <<: *login
        data:
          name: "ansible-cifs-share"
          virtualServerId: 2
          type: "cifs"

      register: result
    - debug: var=result.cifsShare
