namespace: hitachi
name: hnas
version: "1.2.0"
readme: README.md
authors:
- Hitachi Vantara, LTD
description: This collection provides a series of Ansible modules and plugins for interacting with Hitachi NAS storage systems
license_file:
- LICENSE
tags:
- hitachi
- hitachi-vantara
- vsp
- nas
documentation: https://docs.hitachivantara.com/v/u/en-us/nas-platform/mk-92hnas096
homepage: https://www.hitachivantara.com/
build_ignore:
- readme.txt
