namespace: hitachi
name: hnas
version: "1.2.0"
readme: README.md
authors:
- Hitachi Vantara, LTD
description: This collection provides a series of Ansible modules and plugins for interacting with Hitachi NAS storage systems
license_file:
- LICENSE
tags:
- hitachi
- hv
- hitachi_vantara
- vsp
- vsp_one
- storage
- nas
repository: https://github.com/hitachi-vantara/vspone-file-ansible
documentation: https://github.com/hitachi-vantara/vspone-file-ansible
issues: https://github.com/hitachi-vantara/vspone-file-ansible/issues
homepage: https://www.hitachivantara.com/
build_ignore:
- readme.txt
