namespace: hitachi
name: hnas
version: "1.1.0"
readme: README.md
authors:
- Hitachi Vantara, LTD
description: This collection provides a series of Ansible modules and plugins for interacting with Hitachi NAS storage systems
license_file:
- LICENSE
tags:
- collection
documentation: https://support.hitachivantara.com/
homepage: https://www.hitachivantara.com/
build_ignore:
- build_instructions.txt
- checksum.txt
- stuff
- readme.txt
