namespace: "hitachi"
name: "hnas"
version: "1.0.0"
readme: "README.md"
authors:
    - "Hitachi Vantara"
description: "This collection provides a series of Ansible modules and plugins for interacting with Hitachi NAS storage systems"
license:
    - "MIT"
tags:
    - collection
build_ignore:
    - build_instructions.txt
