- name: Ensure a specific Hitachi NAS CIFS share is not present on the server
  hosts: localhost
  gather_facts: false
  collections:
  - hitachivantara.hnas
  vars:
    login: &login
      api_url: https://172.27.5.11:8444/v7
      api_key: BgB2qWZVkE.e53OLShtF3If9UIVdTNmvW9dS7ObPqYNPM83OQoeAj9
      validate_certs: false
  tasks:
  - hnas_share_export:
      state: absent
      <<: *login
      data:
        name: "ansible-cifs-share"
        virtualServerId: 2
        type: "cifs"

    register: result
  - debug: var=result.cifsShare
