- name: Delete Hitachi NAS virtual server
  hosts: localhost
  gather_facts: false
  collections:
  - hitachi.hnas
  vars:
    login: &login
      api_url: https://172.27.5.11:8444/v7
      api_key: BgB2qWZVkE.e53OLShtF3If9UIVdTNmvW9dS7ObPqYNPM83OQoeAj9
      validate_certs: false
  tasks:
  - hnas_virtual_server:
      state: absent
      <<: *login
      data:
        name: "ansible"
    register: result
  - debug: var=result.virtualServer
