- name: Get virtual volume facts for a specific filesystem
  hosts: localhost
  collections:
  - hitachivantara.hnas
  vars:
    login: &login
      api_url: https://172.27.5.11:8444/v7
      api_key: BgB2qWZVkE.e53OLShtF3If9UIVdTNmvW9dS7ObPqYNPM83OQoeAj9
      validate_certs: false
  tasks:
  - hnas_facts: 
      <<: *login
      fact_type:
      - virtual_volume_facts
      data:
        virtualServerId: 1
        filesystemId: "075E75D0D373CA7D0000000000000000"
    register: result
  - debug: var=result
