- name: Expand/ensure Hitachi NAS filesystem is at least 40G - this operation is identical to the create filesystem, but the size should be increased if needed
  hosts: localhost
  gather_facts: false
  collections:
  - hitachi.hnas
  vars:
    login: &login
      api_url: https://172.27.5.11:8444/v7
      api_key: BgB2qWZVkE.e53OLShtF3If9UIVdTNmvW9dS7ObPqYNPM83OQoeAj9
      validate_certs: false
  tasks:
  - hnas_filesystem:
      state: present
      <<: *login
      data:
        label: "ansible"
        virtualServerId: 1
        storage_pool_name: "ansible-pool"
        capacity_unit: gib
        capacity: 40
    register: result
  - debug: var=result.filesystem
